on: [push, pull_request]

name: Build Linux (Release)

jobs:
  build:
    name: OpenBubbles Linux Release
    runs-on: ubuntu-latest

    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Linux build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            clang \
            cmake \
            ninja-build \
            pkg-config \
            libgtk-3-dev \
            liblzma-dev \
            libstdc++-12-dev \
            protobuf-compiler

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.0

      - name: Enable Linux desktop
        run: flutter config --enable-linux-desktop

      - name: Set up fake Fairplay keys
        run: |
          mkdir -p rustpush/certs/fairplay

          cert_names=(
            "4056631661436364584235346952193"
            "4056631661436364584235346952194"
            "4056631661436364584235346952195"
            "4056631661436364584235346952196"
            "4056631661436364584235346952197"
            "4056631661436364584235346952198"
            "4056631661436364584235346952199"
            "4056631661436364584235346952200"
            "4056631661436364584235346952201"
            "4056631661436364584235346952208"
          )

          for name in "${cert_names[@]}"; do
            cp rustpush/certs/legacy-fairplay/fairplay.pem rustpush/certs/fairplay/$name.pem
            cp rustpush/certs/legacy-fairplay/fairplay.crt rustpush/certs/fairplay/$name.crt
          done

      - name: Build Linux app (release)
        run: |
          flutter build linux --release

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: OpenBubbles-Linux-x64-Release
          path: build/linux/x64/release/bundle
